# Generated by Django 5.1.3 on 2024-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('historical-fiction', 'Historical Fiction'), ('science-fiction', 'Science Fiction')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
