# Generated by Django 5.1.3 on 2024-12-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
