# Generated by Django 5.1.3 on 2025-01-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_book_in_stock_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(blank=True, choices=[('like-new', 'Like New'), ('good', 'Good'), ('fair', 'Fair')], max_length=10, null=True),
        ),
    ]
