# Generated by Django 5.1.3 on 2024-12-19 15:42

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, choices=[('like-new', 'Like-New'), ('good', 'Good'), ('fair', 'Fair')], max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('town_or_city', models.CharField(max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_book_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
